#!/usr/bin/env bash

root=`dirname "$0"`

[ $# -ge 1 ] || {
  echo "usage: `basename $0` token ..." >&2
  exit 2
}
tok_name=$1

{
  date \
    && cd "$root" \
    && bash -lc '
      exec alerterr --name=slack-backup-'"$tok_name"' -- \
        flock "/tmp/slack_backup_'"$tok_name"'.lock" \
          ./main "$@"
    ' $0_c.sh "$@"
} 2>&1 | tee "/tmp/slack_backup_$tok_name.log"
