#!/usr/bin/env bash
set -eo pipefail

DEST_ROOT="drive:backup/slack"
windrive="$HOME/windrive"
if ! mountpoint "$windrive"; then
  echo "$windrive is not mounted" >&2
  exit 1
fi
FILES_ROOT="$windrive/backup/slack"

[ $# = 1 ] || {
  echo "usage: `basename $0` token_name" >&2
  exit 2
}
tok_name=$1; shift

echo using token of $tok_name
token=`<tokens/$tok_name tr -d '\n'`

tmp=`mktemp -d`
echo backing up to $tmp
docker run --rm \
  -v "`cd "$tmp" && pwd`":/backup \
  slack-backup --outdir /backup --token "$token"

dest="$DEST_ROOT/$tok_name/`date -u +%Y%m%d%H%M%S`"
echo mkdir $dest
rclone mkdir "$dest"

echo "copy $tmp => $dest"
rclone copy "$tmp" "$dest"

files_dest="$FILES_ROOT/$tok_name/files"
mkdir -p "$files_dest"
echo downloading files to $files_dest
bundle exec ruby dl_files.rb "$tmp" "$files_dest" "$token"

echo deleting $tmp
rm -rf "$tmp"
